const presetStats = {
  Goalkeeper: [
    {
      goals: 0,
      assists: 0,
      yellow_cards: 1,
      red_cards: 0,
      passes_completed: 230,
      key_passes: 2,
      shots_on_target: 0,
      dribbles_attempted: 1,
      dribbles_success: 1,
      dribble_success_rate: 100,
      tackles: 5,
      interceptions: 7,
      duels: 10,
      duels_won: 6,
      rating: 6.8,
    },
    {
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
      passes_completed: 180,
      key_passes: 1,
      shots_on_target: 0,
      dribbles_attempted: 2,
      dribbles_success: 1,
      dribble_success_rate: 50,
      tackles: 4,
      interceptions: 10,
      duels: 12,
      duels_won: 8,
      rating: 7.1,
    },
    {
      goals: 1,
      assists: 1,
      yellow_cards: 1,
      red_cards: 0,
      passes_completed: 290,
      key_passes: 3,
      shots_on_target: 1,
      dribbles_attempted: 4,
      dribbles_success: 2,
      dribble_success_rate: 50,
      tackles: 7,
      interceptions: 9,
      duels: 11,
      duels_won: 7,
      rating: 7.5,
    },
    {
      goals: 0,
      assists: 0,
      yellow_cards: 2,
      red_cards: 0,
      passes_completed: 200,
      key_passes: 0,
      shots_on_target: 0,
      dribbles_attempted: 1,
      dribbles_success: 0,
      dribble_success_rate: 0,
      tackles: 3,
      interceptions: 5,
      duels: 8,
      duels_won: 4,
      rating: 6.5,
    },
  ],
  Defender: [
    {
      goals: 2,
      assists: 1,
      yellow_cards: 3,
      red_cards: 0,
      passes_completed: 560,
      key_passes: 5,
      shots_on_target: 6,
      dribbles_attempted: 20,
      dribbles_success: 12,
      dribble_success_rate: 60,
      tackles: 30,
      interceptions: 25,
      duels: 40,
      duels_won: 28,
      rating: 7.2,
    },
    {
      goals: 1,
      assists: 2,
      yellow_cards: 1,
      red_cards: 0,
      passes_completed: 430,
      key_passes: 3,
      shots_on_target: 4,
      dribbles_attempted: 15,
      dribbles_success: 10,
      dribble_success_rate: 66.6,
      tackles: 24,
      interceptions: 19,
      duels: 38,
      duels_won: 29,
      rating: 7.0,
    },
    {
      goals: 3,
      assists: 0,
      yellow_cards: 4,
      red_cards: 1,
      passes_completed: 490,
      key_passes: 6,
      shots_on_target: 5,
      dribbles_attempted: 18,
      dribbles_success: 12,
      dribble_success_rate: 66.7,
      tackles: 29,
      interceptions: 21,
      duels: 42,
      duels_won: 30,
      rating: 7.4,
    },
    {
      goals: 0,
      assists: 0,
      yellow_cards: 0,
      red_cards: 0,
      passes_completed: 380,
      key_passes: 2,
      shots_on_target: 1,
      dribbles_attempted: 10,
      dribbles_success: 5,
      dribble_success_rate: 50,
      tackles: 15,
      interceptions: 17,
      duels: 33,
      duels_won: 20,
      rating: 6.8,
    },
  ],
  Midfielder: [
    {
      goals: 5,
      assists: 8,
      yellow_cards: 2,
      red_cards: 0,
      passes_completed: 800,
      key_passes: 30,
      shots_on_target: 12,
      dribbles_attempted: 50,
      dribbles_success: 35,
      dribble_success_rate: 70,
      tackles: 20,
      interceptions: 15,
      duels: 55,
      duels_won: 35,
      rating: 7.6,
    },
    {
      goals: 3,
      assists: 5,
      yellow_cards: 3,
      red_cards: 0,
      passes_completed: 720,
      key_passes: 25,
      shots_on_target: 9,
      dribbles_attempted: 40,
      dribbles_success: 28,
      dribble_success_rate: 70,
      tackles: 18,
      interceptions: 14,
      duels: 48,
      duels_won: 32,
      rating: 7.3,
    },
    {
      goals: 6,
      assists: 10,
      yellow_cards: 1,
      red_cards: 0,
      passes_completed: 850,
      key_passes: 35,
      shots_on_target: 14,
      dribbles_attempted: 55,
      dribbles_success: 40,
      dribble_success_rate: 72.7,
      tackles: 25,
      interceptions: 17,
      duels: 60,
      duels_won: 40,
      rating: 8.0,
    },
    {
      goals: 4,
      assists: 4,
      yellow_cards: 0,
      red_cards: 0,
      passes_completed: 650,
      key_passes: 20,
      shots_on_target: 10,
      dribbles_attempted: 30,
      dribbles_success: 20,
      dribble_success_rate: 66.6,
      tackles: 16,
      interceptions: 12,
      duels: 45,
      duels_won: 25,
      rating: 7.0,
    },
  ],
  Attacker: [
    {
      goals: 15,
      assists: 6,
      yellow_cards: 1,
      red_cards: 0,
      passes_completed: 320,
      key_passes: 18,
      shots_on_target: 40,
      dribbles_attempted: 60,
      dribbles_success: 45,
      dribble_success_rate: 75,
      tackles: 5,
      interceptions: 4,
      duels: 50,
      duels_won: 30,
      rating: 8.2,
    },
    {
      goals: 12,
      assists: 4,
      yellow_cards: 2,
      red_cards: 0,
      passes_completed: 310,
      key_passes: 14,
      shots_on_target: 35,
      dribbles_attempted: 50,
      dribbles_success: 36,
      dribble_success_rate: 72,
      tackles: 4,
      interceptions: 3,
      duels: 48,
      duels_won: 28,
      rating: 7.9,
    },
    {
      goals: 18,
      assists: 7,
      yellow_cards: 1,
      red_cards: 1,
      passes_completed: 350,
      key_passes: 22,
      shots_on_target: 48,
      dribbles_attempted: 70,
      dribbles_success: 50,
      dribble_success_rate: 71.4,
      tackles: 6,
      interceptions: 5,
      duels: 55,
      duels_won: 35,
      rating: 8.5,
    },
    {
      goals: 10,
      assists: 3,
      yellow_cards: 0,
      red_cards: 0,
      passes_completed: 280,
      key_passes: 10,
      shots_on_target: 25,
      dribbles_attempted: 40,
      dribbles_success: 28,
      dribble_success_rate: 70,
      tackles: 3,
      interceptions: 2,
      duels: 42,
      duels_won: 24,
      rating: 7.4,
    },
  ],
};

module.exports = presetStats;
